### ISSUE TITLE
扫描登录之后就暂时没有别的了吗？

### ISSUE THREAD

**Issue by rzl** [think2011/vue-web-wechat#1]
在VUE里里面这样的写法没有问题
...params,

但是在代理配置那里就提示语法错误 
...baseProxyTable,

**Comment by think2011** [comment]
恩，暂时搁置了


> 但是在代理配置那里就提示语法错误
...baseProxyTable,

这个问题可能是你用的node版本有关， vue里的是经过babel转成es5语法的，配置文件是经过node的，node的旧版本不支持这个语法
